/// Flutter icons IconMedmapHome
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconMedmapHome
///      fonts:
///       - asset: fonts/IconMedmapHome.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IconMedmap {
  IconMedmap._();

  static const _kFontFam = 'IconMedmapHome';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tenders =
      IconData(0xe800, fontFamily: 'IconMedmapTenders', fontPackage: _kFontPkg);

  static const IconData products = IconData(0xe800,
      fontFamily: 'IconMedmapProducts', fontPackage: _kFontPkg);

  static const IconData distributors = IconData(0xe800,
      fontFamily: 'IconMedmapDistributors', fontPackage: _kFontPkg);
}
